// resources/js/Components/elements/shopcard.jsx
import {useState} from "react";
import Modal from "@/Components/Modal";
import axios from "axios";

function ShopCard({auth, shop}) {
    const [selectedItem, setSelectedItem] = useState(null);
    const [isModalOpen, setIsModalOpen] = useState(false);

    const handleModalClose = () => {
        setSelectedItem(null);
        setIsModalOpen(false);
    };

    const handleBuyBtnClick = async (itemId) => {
        try {
            const response = await axios.post(
                "/getItemInfo",
                {
                    itemid: itemId,
                },
                {
                    headers: {
                        "Content-Type": "application/json",
                    },
                }
            );
            const data = response.data;
            setSelectedItem(data);
            setIsModalOpen(true);
        } catch (error) {
            console.error(error);
        }
    };

    const handleBuyItem = async (itemId) => {
        try {
            const response = await axios.post(
                "/buyItem",
                {
                    itemid: itemId,
                },
                {
                    headers: {
                        "Content-Type": "application/json",
                    },
                }
            );
            console.log("Item bought successfully");
        } catch (error) {
            console.error(error);
        }
    };


    return (
        <>
            <Modal auth={auth} selectedItem={selectedItem} handleModalClose={handleModalClose}
                   handleBuyItem={handleBuyItem}/>

            <div
                className="grid grid-flow-row gap-8 text-neutral-600 bg-base-300 p-8 shadow-2xl sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                {shop.map((item) => (
                    <div key={item.id} className="card w-72 bg-base-200 shadow-xl">
                        <figure className="p-4">
                            <img className="w-72" src={item.image} alt={item.name}/>
                        </figure>
                        <div className="card-body">
                            <h2 className="card-title text-base-content">{item.name}</h2>
                            <p className="text-base-content">{item.about}</p>
                            <label onClick={() => handleBuyBtnClick(item.id)} htmlFor="my-modal"
                                   className="btn btn-primary w-auto">Buy</label>
                        </div>
                    </div>
                ))}
            </div>

        </>
    );
}

export default ShopCard;

// resources/js/Components/User/Elements/ShopCard.vue
<template>
    <ShopModal :selectedItem="selectedItem" />

    <div class="flex">
        <input v-model="search" type="text" class="input w-full max-w-xs rounded-none flex m-auto" placeholder="Search by name" />
    </div>
    <div class="grid grid-flow-row gap-8 text-neutral-600 bg-base-300 p-8 shadow-2xl sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 mb-10">
        <div v-for="item in filteredItems" :key="item.id" class="card w-72 bg-base-200 shadow-xl">
            <figure class="p-4">
                <img class="w-72" :src="item.image" :alt="item.name" />
            </figure>
            <div class="card-body">
                <h2 class="card-title text-base-content">{{ item.name }}</h2>
                <p class="text-base-content">{{ item.about }}</p>
                <label for="shop-modal" class="btn btn-primary w-auto" @click="selectItem(item)">Buy</label>
            </div>
        </div>
    </div>
</template>
<script lang="ts">
import { defineComponent } from 'vue'
import ShopModal from "@/Components/User/Modals/Shop.vue";
import axios from "axios";

interface Item {
    id: number
    name: string
    about: string
    image: string
    category: string
}

export default defineComponent({
    name: "ShopCard",
    components: { ShopModal },
    props: {
        Items: {
            required: true,
        },
    },
    data() {
        return {
            selectedItem: null as Item | null,
            search: "",
        };
    },
    computed: {
        filteredItems(): Item[] {
            let items = this.Items;
            if (this.search) {
                items = items.filter((item) =>
                    item.name.toLowerCase().includes(this.search.toLowerCase())
                );
            }
            return items;
        },
    },
    methods: {
        selectItem(item: Item) {
            this.selectedItem = item;
            axios
                .post("/getItemInfo", { itemid: item.id })
                .then((response) => {
                    this.selectedItem = response.data;
                })
                .catch((error) => {
                    console.log(error);
                });
        },
    },
});
</script>
